# Copyright 2026 Ericsson AB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load(
    "@rules_cc//cc:defs.bzl",
    "cc_library",
)
load(
    "//:defs.bzl",
    "codechecker_test",
    "store",
)

cc_library(
    name = "c_target",
    srcs = ["simple.c"],
    tags = ["manual"],
)

codechecker_test(
    name = "codechecker",
    tags = ["manual"],
    targets = [
        "c_target",
    ],
)

store(
    name = "store",
    testonly = True,
    tags = ["manual"],
    targets = [
        ":codechecker",
    ],
)
